### ISSUE TITLE
[调查]你是怎么知道caddy的？

### ISSUE THREAD

**Issue by comdeng** [phpple/caddy-cn-doc#1]
大家都是通过什么渠道了解到caddy的呢？
你对caddy最深的印象是什么呢？

**Comment by iTanken** [comment]
配置 Nginx 的 SSL 时无意间发现的。
请问一下 `DNS验证` 中的服务商有没有阿里云的？

**Comment by comdeng** [comment]
> 配置 Nginx 的 SSL 时无意间发现的。
> 请问一下 `DNS验证` 中的服务商有没有阿里云的？

在官网上还没有发现。

**Comment by lx1036** [comment]
研究 Kubernetes/Prometheus 知道的 CoreDNS，研究 CoreDNS 时知道的 Caddy Server。

**Comment by arguskao** [comment]
看到網路上人家介紹的！但是好像沒辦法用！

**Comment by comdeng** [comment]
具体遇到什么问题呢？

**Comment by arguskao** [comment]
> 具体遇到什么问题呢？

問題可多了，有時候安裝就會碰到奇怪的問題，然後找不到解決，於是就放棄了。

**Comment by lx1036** [comment]
@arguskao caddy 是 go 写的，安装很方便啊。caddy 好东西，别放弃使用。

**Comment by comdeng** [comment]
> @arguskao caddy 是 go 写的，安装很方便啊。caddy 好东西，别放弃使用。

是的，用起来很方便

**Comment by idweball** [comment]
使用v2ray翻墙时了解到
