### ISSUE TITLE
http.proxy 似乎没有翻译

### ISSUE THREAD

**Issue by CaiJingLong** [phpple/caddy-cn-doc#2]
是故意如此的吗

https://dengxiaolong.com/caddy/zh/http.proxy.html

这个页面 我这里看是这样的

![image](https://user-images.githubusercontent.com/14145407/50735580-6a9ae180-11ec-11e9-8c21-c52b2ff1acbc.png)

**Comment by comdeng** [comment]
已经更新好，感谢反馈！

**Comment by CaiJingLong** [comment]
感谢你的辛勤劳动!
